directories:
  output: ./releases
  buildResources: build
productName: TabStein
appId: com.tableau.jhegele.tabstein
icon: ./assets/icons/icon.png
mac:
  category: public.app-category.utilities
  target:
    - target: dmg
      arch: x64
win:
  target:
    - target: nsis
      arch: x64
files:
  - filter:
      - dist/**/*
      - '!node_modules${/*}'
      - '!dist/*.map'
asar: true
removePackageScripts: true
electronVersion: 8.2.5
